"""
boptx ASC-only calibration for Lyon eqasim-france pipeline.

Adapted from bavaria/.../calibrate_eqasim_asc_only.py v4.

Key differences from Bavaria:
  - eqasim-france (ile_de_france) has NO Munich-specific penalty stack.
    IDFModeParameters.buildDefault() provides clean, IDF-paper-calibrated
    defaults. No bavariaPt.onlyBus_u / betaDrivingPermit_u to pin.
  - car_passenger is activated per-person via isPassenger attribute
    (IDFModeAvailability), but has no separate ASC in IDFModeParameters.
    Calibrate 4 ASCs (car ref frozen) + walk/bike betaTT: 5 free params.
  - Additional IDF-specific urban-area betas available but not tuned here:
    idfCar.betaInsideUrbanArea, idfCar.betaCrossingUrbanArea,
    idfBike.betaInsideUrbanArea.

Calibration target:
  Lyon-region ENTD 2008 trip shares by distance band (built by
  build_lyon_target.py — see data/README.md). Falls back to national
  ENTD shares if Lyon subset is too thin.

Prerequisites:
  1. 1% Lyon MATSim scenario in output_1pct/ (produced by
     eqasim-france pipeline with sampling_rate=0.01, run_matsim=false)
  2. eqasim-ile-de-france run.jar (auto-built by pipeline,
     at output_1pct/lyon_1pct_run.jar)
  3. Lyon mode-share target pickle at data/lyon_entd_shares.pkl

Usage:
  cd matsim_scenarios/eqasim-france/calibration/boptx
  # build target once (or after ENTD source changes):
  ../../.venv/Scripts/python build_lyon_target.py
  # run calibration:
  ../../.venv/Scripts/python calibrate_lyon_1pct.py [parallelism] [threads]
"""

import os
import sys
import logging

logging.basicConfig(level=logging.INFO)

# boptx lives in the Bavaria sibling — reuse instead of duplicating.
REPO_ROOT = os.path.realpath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
BOPTX_SRC = os.path.join(
    REPO_ROOT, "matsim_scenarios", "bavaria", "calibration", "boptx", "boptx-upstream", "src"
)
sys.path.insert(0, BOPTX_SRC)
sys.path.insert(0, os.path.join(BOPTX_SRC, "boptx", "eqasim"))
sys.path.insert(0, os.path.join(BOPTX_SRC, "boptx", "matsim"))

from objectives import ModeShareObjective
from problem import ModeParameter, CalibrationProblem, LinearPenaltyCalculator
from boptx.algorithms import DifferentialEvolutionAlgorithm
from matsim import MATSimEvaluator
from boptx.loop import Loop
from boptx.tracker import Tracker, PickleTracker

# === Parse arguments ===
PARALLELISM = int(sys.argv[1]) if len(sys.argv) > 1 else 1
THREADS = int(sys.argv[2]) if len(sys.argv) > 2 else 8

os.environ["JAVA_TOOL_OPTIONS"] = "-Djava.awt.headless=true"

# === Paths ===
SCENARIO_DIR = os.path.realpath(os.path.join(
    REPO_ROOT, "matsim_scenarios", "eqasim-france", "output_1pct"
))
# ASC-only config variant: DiscreteModeChoice weight = 1.0, KeepLastSelected = 0.
# Every agent picks a fresh mode every evaluation — no 95% warm-start noise
# floor from the generated config's multi-iter defaults. Generated by
# `make_asc_only_config.py` (idempotent).
CONFIG_PATH = os.path.join(SCENARIO_DIR, "lyon_1pct_asc_only_config.xml")
POPULATION_PATH = os.path.join(SCENARIO_DIR, "lyon_1pct_population.xml.gz")
JAR_PATH = os.path.join(SCENARIO_DIR, "lyon_1pct_run.jar")
# Must match the JDK that built the eqasim JAR (config_100pct.yml / config_1pct.yml
# use JDK 25). JAR class file version 69.0 — needs JDK 25 runtime.
JAVA_BINARY = "C:/Users/VWAUCCY/dev/msf/.jdk/jdk-25.0.2+10/bin/java.exe"

# === Objective ===
# Lyon-region ENTD 2008 mode shares by distance band, built by
# build_lyon_target.py from the cached filtered ENTD trips.
mode_share_objective = ModeShareObjective(
    "data/reference_trips.csv",
    dict(
        modes=["car", "pt", "bicycle", "walk", "car_passenger"],
        maximum_bin_count=20,
    ),
    objective="L1",
    shares_path="data/lyon_entd_shares.pkl",
)

penalty = LinearPenaltyCalculator(100.0, 10.0)

WORK_DIR = "work_lyon_1pct"
os.makedirs(WORK_DIR, exist_ok=True)

# === Parameters ===
# Reference mode: PT (pt.alpha_u FIXED at 0 via CLI). All other ASCs express
# utility relative to PT. This sets up clean DRT seeding later: DRT is seeded
# from PT params (conservative — PT's waiting-time penalty realistically applies
# to DRT, no car-ASC head start). With PT at 0, DRT's initial ASC (PT-seeded)
# is also 0 — DRT sits naturally in PT's utility neighborhood.
#
# IDF defaults (IDFModeParameters.buildDefault) — already expressed relative to
# the eqasim-france convention where PT defaults to 0:
#   pt.alpha_u                  =  0.00   (frozen — reference)
#   pt.betaInVehicleTime_u_min  = -0.017  (frozen)
#   car.alpha_u                 = +1.35   (free — Lyon is car-heavy, likely grows)
#   car.betaTravelTime_u_min    = -0.06   (frozen)
#   bike.alpha_u                = -2.00   (free)
#   bike.betaTravelTime_u_min   = -0.05   (frozen; free only if needed)
#   walk.alpha_u                = +1.43   (free)
#   walk.betaTravelTime_u_min   = -0.15   (frozen; free only if needed)
#   motorcycle.alpha_u          = +1.35   (frozen at IDF default; rare in pop)
#
# Bounds straddle each IDF default with ±2 utils of room.
#
# car_passenger has NO ASC — it uses ZeroUtilityEstimator in the generated
# Lyon config (eqasim-ile-de-france, line 252-254). Its share emerges from
# per-person `isPassenger` availability + zero utility vs the calibrated modes.
# To tune car_passenger would require replacing the estimator (Java patch).
#
# betaTT params deliberately frozen at IDF defaults in v1. Free them only if
# the ASC-only calibration leaves systematic per-distance-band residuals
# (e.g. walk over at 0.5-2 km or bike over at 5-50 km, as seen in Bavaria).
parameters = [
    ModeParameter("car.alpha_u",          bounds=(-0.50,  4.00), initial_value=+1.35),
    ModeParameter("bike.alpha_u",         bounds=(-4.00,  0.00), initial_value=-2.00),
    ModeParameter("walk.alpha_u",         bounds=(-1.00,  4.00), initial_value=+1.43),
    # pt.alpha_u           FIXED at 0   via CLI (reference mode)
    # motorcycle.alpha_u   FIXED at IDF default (+1.35) via CLI
    # walk.betaTravelTime  FIXED at -0.15 (free only if residuals demand)
    # bike.betaTravelTime  FIXED at -0.05 (free only if residuals demand)
]

problem = CalibrationProblem(mode_share_objective, parameters=parameters, penalty=penalty)

# === Algorithm ===
algorithm = DifferentialEvolutionAlgorithm(problem, candidates=8)

# === Evaluator ===
evaluator = MATSimEvaluator(
    working_directory=WORK_DIR,
    problem=problem,
    parallelism=PARALLELISM,
    settings=dict(
        class_path=JAR_PATH,
        main_class="org.eqasim.ile_de_france.RunSimulation",
        # 1% Lyon = ~18k persons; 8g heap is ample, leaves slack on 128 GB box.
        memory="8g",
        java=JAVA_BINARY,
        threads=THREADS,
        iterations=1,
        arguments=[
            "--config-path", CONFIG_PATH,
            "--config:controler.createGraphsInterval", "0",
            "--config:plans.inputPlansFile", POPULATION_PATH,
            # Capacity factors for 1% sample
            "--config:qsim.flowCapacityFactor",    "0.01",
            "--config:qsim.storageCapacityFactor", "0.01",
            # Fix car ASC at 0 — reference alternative, other ASCs are deltas.
            # Reference mode: PT pinned at alpha_u = 0. All other ASCs are
            # utility deltas vs PT. This frames DRT seeding naturally: DRT
            # gets seeded from PT params (PT-reference keeps DRT near PT in
            # utility space rather than forcing it to chase a car baseline).
            "--mode-choice-parameter:pt.alpha_u", "0.0",
            # Motorcycle kept at its IDF default (+1.35, same as car's default).
            # Base Lyon motorcycle share is <1% so not worth tuning; pinning
            # prevents it from drifting with the car parameter.
            "--mode-choice-parameter:motorcycle.alpha_u", "1.35",
        ],
    ),
)


# === Logging tracker with per-eval mode share summary ===
# ENTD 2008 national mode shares (placeholder — replace with Lyon-region targets
# once build_lyon_target.py has emitted shares). For now used only for the
# side-by-side print, NOT for the objective (objective reads from shares_path).
_ENTD_NATIONAL = {"car": 0.65, "car_passenger": 0.09, "walk": 0.18, "bicycle": 0.03, "pt": 0.05}
_MODES_ORDERED = ["car", "walk", "bicycle", "pt", "car_passenger"]


class LoggingTracker(Tracker):
    def __init__(self, pickle_path):
        self._pickle = PickleTracker(pickle_path)
        self._best_obj = float("inf")

    def track(self, state, finished):
        self._pickle.track(state, finished)
        round_no = self._pickle.round - 1

        non_transitional = [e for e in finished if not e.is_transitional()]
        if not non_transitional:
            return

        for ev in non_transitional:
            obj = ev.get_objective()
            vals = ev.get_values()
            marker = ""
            if obj < self._best_obj:
                self._best_obj = obj
                marker = "  *** NEW BEST ***"

            shares = self._mode_shares(ev.get_information())
            param_str = "  ".join(
                f"{p.parameter}={v:+.4f}" for p, v in zip(parameters, vals)
            )
            share_str = "  ".join(
                f"{m[:4]}={shares.get(m, 0.0):.3f}(ref={_ENTD_NATIONAL.get(m, 0.0):.3f})"
                for m in _MODES_ORDERED
            )
            print(f"[R{round_no:03d}] obj={obj:.6f}{marker}")
            print(f"  params: {param_str}")
            print(f"  shares: {share_str}")

        if round_no > 0 and round_no % 20 == 0:
            print(f"\n--- Best after round {round_no}: {self._best_obj:.6f} ---\n")

    @staticmethod
    def _mode_shares(info):
        try:
            df = info["matsim"]["objective"]["configuration"]["data"]
            return {
                m: float(df[df["mode"] == m]["simulation_share"].mean())
                for m in _MODES_ORDERED
            }
        except Exception:
            return {}


# === Run ===
print("=" * 70)
print("Lyon eqasim-france ASC Calibration (1% scenario)")
print("=" * 70)
print(f"  Parallelism:  {PARALLELISM}")
print(f"  Threads/eval: {THREADS}")
print(f"  DE candidates: 8   max_evals: 400")
print(f"  Scenario:     {SCENARIO_DIR}")
print(f"  JAR:          {JAR_PATH}")
print(f"  Pinned via CLI:")
print(f"    pt.alpha_u         = 0.00  (reference — sets up clean DRT seeding)")
print(f"    motorcycle.alpha_u = 1.35  (IDF default; <1% share, not worth tuning)")
print(f"  Structurally fixed (cannot tune via CLI):")
print(f"    car_passenger = ZeroUtilityEstimator (no ASC field — Java patch needed)")
print(f"  Free parameters ({len(parameters)}):")
for p in parameters:
    print(f"    {p.parameter:40s}  init={p.initial_value:+.6f}  bounds={p.bounds}")
print(f"  Objective: ENTD Lyon-region mode shares by distance band (L1)")
print("=" * 70)

tracker = LoggingTracker("optimization_lyon_1pct.p")

Loop(
    algorithm=algorithm,
    evaluator=evaluator,
    maximum_evaluations=400,
).advance(callback=tracker)
